name: Zeit Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.16.0
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.0'
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
      - name: deploy to zeit
        run: npm run deploy-prod
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
